# -*- coding: utf-8 -*-
"""GuessTheNumber.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ID9Ofhy2vPsD8WYPoATtyoJUsycjGAsP
"""

# Empty list to store tasks
tasks = []

# Function to add a task
def add_task():
    task = input("Enter a task: ")
    tasks.append(task)
    print("Task added successfully!")

# Function to view all tasks
def view_tasks():
    if len(tasks) == 0:
        print("No tasks found.")
    else:
        print("Tasks:")
        for index, task in enumerate(tasks, start=1):
            print(f"{index}. {task}")

# Function to remove a task
def remove_task():
    view_tasks()
    if len(tasks) == 0:
        return
    task_index = int(input("Enter the index of the task to remove: ")) - 1
    if task_index < 0 or task_index >= len(tasks):
        print("Invalid task index.")
    else:
        removed_task = tasks.pop(task_index)
        print(f"Task '{removed_task}' removed successfully!")

# Main program loop
while True:
    print("\n--- To-Do List ---")
    print("1. Add task")
    print("2. View tasks")
    print("3. Remove task")
    print("4. Quit")

    choice = input("Enter your choice (1-4): ")

    if choice == "1":
        add_task()
    elif choice == "2":
        view_tasks()
    elif choice == "3":
        remove_task()
    elif choice == "4":
        print("Quitting program...")
        break
    else:
        print("Invalid choice. Please try again.")

print("Goodbye!")