# -*- coding: utf-8 -*-
"""GuessTheNumber.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ID9Ofhy2vPsD8WYPoATtyoJUsycjGAsP
"""

questions = {

    "Arts and Culture": [
     {
        "question": "Which famous artist painted the Mona Lisa?",
        "options": ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Michelangelo"],
        "answer": "Leonardo da Vinci"
    },
    {
        "question": "What is the technique of making designs by cutting paper called?",
        "options": ["Origami", "Quilling", "Decoupage", "Kirigami"],
        "answer": "Kirigami"
    },
    {
        "question": "Who is famous for creating the sculpture 'David'?",
        "options": ["Auguste Rodin", "Donatello", "Michelangelo", "Antonio Canova"],
        "answer": "Michelangelo"
    },
    {
        "question": "Which art movement is characterized by dreamlike and surreal imagery?",
        "options": ["Cubism", "Dadaism", "Surrealism", "Impressionism"],
        "answer": "Surrealism"
    },
    {
        "question": "What material is traditionally used in the art of pottery?",
        "options": ["Clay", "Wood", "Metal", "Glass"],
        "answer": "Clay"
    },
    {
        "question": "Which artist is known for his 'Campbell's Soup Cans' artwork?",
        "options": ["Andy Warhol", "Jackson Pollock", "Salvador Dali", "Claude Monet"],
        "answer": "Andy Warhol"
    },
    {
        "question": "What is the Japanese art of flower arrangement called?",
        "options": ["Bonsai", "Sumi-e", "Ikebana", "Haiku"],
        "answer": "Ikebana"
    },
    {
        "question": "Who painted the famous ceiling of the Sistine Chapel?",
        "options": ["Pablo Picasso", "Michelangelo", "Claude Monet", "Vincent van Gogh"],
        "answer": "Michelangelo"
    },
    {
        "question": "What type of paint uses egg yolk as a binder?",
        "options": ["Watercolor", "Acrylic", "Gouache", "Tempera"],
        "answer": "Tempera"
    },
    {
        "question": "Which artist is famous for his 'Starry Night' painting?",
        "options": ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"],
        "answer": "Vincent van Gogh"
    },
    {
        "question": "What is the Japanese art of paper folding called?",
        "options": ["Kirigami", "Decoupage", "Quilling", "Origami"],
        "answer": "Origami"
    },
    {
        "question": "Who sculpted the statue of 'The Thinker'?",
        "options": ["Auguste Rodin", "Donatello", "Michelangelo", "Antonio Canova"],
        "answer": "Auguste Rodin"
    },
    {
        "question": "Which art movement focuses on geometric shapes and patterns?",
        "options": ["Cubism", "Dadaism", "Impressionism", "Surrealism"],
        "answer": "Cubism"
    },
    {
        "question": "What is the art of decorative handwriting called?",
        "options": ["Calligraphy", "Typography", "Graffiti", "Chiaroscuro"],
        "answer": "Calligraphy"
    },
    {
        "question": "Who painted the famous mural 'Guernica'?",
        "options": ["Salvador Dali", "Jackson Pollock", "Pablo Picasso", "Claude Monet"],
        "answer": "Pablo Picasso"
    },
    {
        "question": "What is the technique of decorating metal with enamel called?",
        "options": ["Decoupage", "Mosaic", "Fresco", "Cloisonné"],
        "answer": "Cloisonné"
    },
    {
        "question": "Which artist is known for his drip painting technique?",
        "options": ["Andy Warhol", "Jackson Pollock", "Salvador Dali", "Claude Monet"],
        "answer": "Jackson Pollock"
    },
    {
        "question": "What is the art of arranging and gluing paper cutouts onto a surface called?",
        "options": ["Quilling", "Collage", "Decoupage", "Mosaic"],
        "answer": "Decoupage"
    },
    {
        "question": "Who painted the famous mural 'The Last Supper'?",
        "options": ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Michelangelo"],
        "answer": "Leonardo da Vinci"
    },
    {
        "question": "Which art movement emphasizes the spontaneous and subconscious?",
        "options": ["Cubism", "Dadaism", "Impressionism", "Surrealism"],
        "answer": "Dadaism"
    }
    ],

    "Funny" :
     [{
        "question": "Why did the scarecrow win an award?",
        "options": ["Because he was outstanding in his field.", "Because he had a great sense of humor.", "Because he could scare away birds.", "Because he could dance."],
        "answer": "Because he was outstanding in his field."
    },
    {
        "question": "Why don't skeletons fight each other?",
        "options": ["Because they're all bone and no muscle.", "Because they're too scared.", "Because they don't have the guts.", "Because they're too busy dancing."],
        "answer": "Because they don't have the guts."
    },
    {
        "question": "What did the ocean say to the beach?",
        "options": ["Nothing, it just waved.", "You're so sandy!", "Let's go for a swim.", "I'm feeling salty today."],
        "answer": "Nothing, it just waved."
    },
    {
        "question": "Why don't scientists trust atoms?",
        "options": ["Because they make up everything.", "Because they're too small to see.", "Because they're always changing.", "Because they're too boring."],
        "answer": "Because they make up everything."
    },
    {
        "question": "Why did the tomato turn red?",
        "options": ["Because it saw the salad dressing.", "Because it was blushing.", "Because it was ripe.", "Because it was angry."],
        "answer": "Because it saw the salad dressing."
    },
    {
        "question": "What did one wall say to the other wall?",
        "options": ["I'll meet you at the corner.", "I'm feeling plastered.", "I'm tired of holding up this house.", "Let's paint a mural together."],
        "answer": "I'll meet you at the corner."
    },
    {
        "question": "Why don't elephants use computers?",
        "options": ["Because they're afraid of the mouse.", "Because their trunks can't type.", "Because they prefer typewriters.", "Because they don't have internet access."],
        "answer": "Because they're afraid of the mouse."
    },
    {
        "question": "What do you call a bear with no teeth?",
        "options": ["A gummy bear.", "A toothless bear.", "A hungry bear.", "A silly bear."],
        "answer": "A gummy bear."
    },
    {
        "question": "Why did the bicycle fall over?",
        "options": ["Because it was tired.", "Because it had too many wheels.", "Because it was a unicycle.", "Because it saw a squirrel."],
        "answer": "Because it was two-tired."
    },
    {
        "question": "What's the best way to carve wood?",
        "options": ["With a chainsaw.", "With a spoon.", "With a butter knife.", "With a laser beam."],
        "answer": "With a butter knife."
    },
    {
        "question": "What do you get when you cross a snowman and a vampire?",
        "options": ["Frostbite.", "A cold bite.", "A snow fang.", "Frosty the vampire."],
        "answer": "Frostbite."
    },
    {
        "question": "Why did the golfer bring two pairs of pants?",
        "options": ["In case he got a hole in one.", "In case he got a hole in his pants.", "In case he needed to change.", "In case he wanted to look fashionable."],
        "answer": "In case he got a hole in one."
    },
    {
        "question": "Why did the tomato turn green?",
        "options": ["Because it was unripe.", "Because it was envious.", "Because it wanted to be a cucumber.", "Because it was sick."],
        "answer": "Because it was unripe."
    },
    {
        "question": "Why don't scientists trust atoms anymore?",
        "options": ["Because they're always making jokes.", "Because they're too smart.", "Because they're too unpredictable.", "Because they've become rebellious."],
        "answer": "Because they make up everything."
    },
    {
        "question": "What's the most musical part of a fish?",
        "options": ["The scales.", "The fins.", "The gills.", "The bubbles."],
        "answer": "The scales."
    },
    {
        "question": "Why did the tomato turn into a salad?",
        "options": ["Because it wanted to be healthy.", "Because it got tired of being a fruit.", "Because it met a lettuce.", "Because it needed more friends."],
        "answer": "Because it saw the salad dressing."
    },
    {
        "question": "Why was the math book sad?",
        "options": ["Because it had too many problems.", "Because it couldn't solve a problem.", "Because it was missing a page.", "Because it needed a hug."],
        "answer": "Because it had too many problems."
    },
    {
        "question": "What's orange and sounds like a parrot?",
        "options": ["A carrot.", "A parrot painted orange.", "An orange parrot.", "A talking fruit."],
        "answer": "A carrot."
    },
    {
        "question": "Why was the computer cold?",
        "options": ["Because it left its Windows open.", "Because it was made of ice.", "Because it was snowing inside.", "Because it had a virus."],
        "answer": "Because it left its Windows open."
    },
    {
        "question": "What do you call a fake noodle?",
        "options": ["An impasta.", "A faux noodle.", "A spoodle.", "A noodle imposter."],
        "answer": "An impasta."
    },
    {
        "question": "Why don't scientists trust atoms anymore?",
        "options": ["Because they're too small to see.", "Because they're too unpredictable.", "Because they're always bonding.", "Because they're full of energy."],
        "answer": "Because they make up everything."
    }
     ],

    "Geography":
     [{
        "question": "What is the capital of Australia?",
        "options": ["Sydney", "Melbourne", "Canberra", "Perth"],
        "answer": "Canberra"
    },
    {
        "question": "Which country is known as the 'Land of the Rising Sun'?",
        "options": ["China", "Japan", "South Korea", "Thailand"],
        "answer": "Japan"
    },
    {
        "question": "What is the largest desert in the world?",
        "options": ["Sahara Desert", "Gobi Desert", "Arabian Desert", "Antarctic Desert"],
        "answer": "Antarctic Desert"
    },
    {
        "question": "Which is the longest river in the world?",
        "options": ["Nile River", "Amazon River", "Yangtze River", "Mississippi River"],
        "answer": "Nile River"
    },
    {
        "question": "What is the capital of Canada?",
        "options": ["Toronto", "Vancouver", "Ottawa", "Montreal"],
        "answer": "Ottawa"
    },
    {
        "question": "Which city is known as the 'Eternal City'?",
        "options": ["Athens", "Rome", "Paris", "Cairo"],
        "answer": "Rome"
    },
    {
        "question": "Which African country is famous for its pyramids?",
        "options": ["Kenya", "Egypt", "Nigeria", "South Africa"],
        "answer": "Egypt"
    },
    {
        "question": "Which is the largest ocean in the world?",
        "options": ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
        "answer": "Pacific Ocean"
    },
    {
        "question": "What is the highest mountain in the world?",
        "options": ["Mount Kilimanjaro", "Mount Everest", "Mount McKinley", "Mount Fuji"],
        "answer": "Mount Everest"
    },
    {
        "question": "Which is the smallest country in the world?",
        "options": ["Monaco", "Vatican City", "San Marino", "Liechtenstein"],
        "answer": "Vatican City"
    },
    {
        "question": "What is the official language of Brazil?",
        "options": ["Spanish", "English", "Portuguese", "French"],
        "answer": "Portuguese"
    },
    {
        "question": "Which is the largest country by land area?",
        "options": ["United States", "China", "Russia", "Canada"],
        "answer": "Russia"
    },
    {
        "question": "What is the largest island in the Mediterranean Sea?",
        "options": ["Cyprus", "Crete", "Corsica", "Sicily"],
        "answer": "Sicily"
    },
    {
        "question": "Which is the driest place on Earth?",
        "options": ["Sahara Desert", "Atacama Desert", "Gobi Desert", "Namib Desert"],
        "answer": "Atacama Desert"
    },
    {
        "question": "What is the capital of South Africa?",
        "options": ["Johannesburg", "Cape Town", "Durban", "Pretoria"],
        "answer": "Pretoria"
    },
    {
        "question": "Which is the largest waterfall in the world?",
        "options": ["Angel Falls", "Iguazu Falls", "Niagara Falls", "Victoria Falls"],
        "answer": "Angel Falls"
    },
    {
        "question": "What is the official language of China?",
        "options": ["Mandarin", "Cantonese", "Shanghainese", "Hokkien"],
        "answer": "Mandarin"
    },
    {
        "question": "Which is the largest city in the United States?",
        "options": ["New York City", "Los Angeles", "Chicago", "Houston"],
        "answer": "New York City"
    },
    {
        "question": "What is the largest lake in Africa?",
        "options": ["Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Chad"],
        "answer": "Lake Victoria"
    },
    {
        "question": "Which country is known as the 'Land of Fire and Ice'?",
        "options": ["Iceland", "Greenland", "Norway", "Finland"],
        "answer": "Iceland"
    }],

    "History" :
     [{
        "question": "Who was the first President of the United States?",
        "options": ["George Washington", "Thomas Jefferson", "John Adams", "Abraham Lincoln"],
        "answer": "George Washington"
    },
    {
        "question": "In which year did World War II end?",
        "options": ["1942", "1944", "1945", "1946"],
        "answer": "1945"
    },
    {
        "question": "Who was the leader of the Soviet Union during World War II?",
        "options": ["Joseph Stalin", "Vladimir Lenin", "Mikhail Gorbachev", "Nikita Khrushchev"],
        "answer": "Joseph Stalin"
    },
    {
        "question": "Which country was responsible for the construction of the Great Wall?",
        "options": ["China", "India", "Egypt", "Greece"],
        "answer": "China"
    },
    {
        "question": "Who wrote the play 'Romeo and Juliet'?",
        "options": ["William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"],
        "answer": "William Shakespeare"
    },
    {
        "question": "What was the period of political and social upheaval in France known as?",
        "options": ["The Renaissance", "The Enlightenment", "The Industrial Revolution", "The French Revolution"],
        "answer": "The French Revolution"
    },
    {
        "question": "Who painted the ceiling of the Sistine Chapel?",
        "options": ["Leonardo da Vinci", "Vincent van Gogh", "Michelangelo", "Pablo Picasso"],
        "answer": "Michelangelo"
    },
    {
        "question": "Which civilization built the ancient city of Machu Picchu?",
        "options": ["Aztec", "Maya", "Inca", "Egyptian"],
        "answer": "Inca"
    },
    {
        "question": "Who invented the telephone?",
        "options": ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Albert Einstein"],
        "answer": "Alexander Graham Bell"
    },
    {
        "question": "Which country colonized a large part of Africa during the Scramble for Africa?",
        "options": ["United Kingdom", "France", "Germany", "Spain"],
        "answer": "United Kingdom"
    },
    {
        "question": "Who was the first person to set foot on the moon?",
        "options": ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Alan Shepard"],
        "answer": "Neil Armstrong"
    },
    {
        "question": "Which war was fought between the North and the South regions of the United States?",
        "options": ["American Revolution", "Civil War", "World War I", "Vietnam War"],
        "answer": "Civil War"
    },
    {
        "question": "Which city hosted the first modern Olympic Games in 1896?",
        "options": ["London", "Paris", "Athens", "Rome"],
        "answer": "Athens"
    },
    {
        "question": "Who was the first female Prime Minister of the United Kingdom?",
        "options": ["Margaret Thatcher", "Angela Merkel", "Theresa May", "Indira Gandhi"],
        "answer": "Margaret Thatcher"
    },
    {
        "question": "Which ancient civilization built the city of Rome?",
        "options": ["Greeks", "Romans", "Persians", "Etruscans"],
        "answer": "Romans"
    },
    {
        "question": "Who was the leader of Nazi Germany during World War II?",
        "options": ["Adolf Hitler", "Benito Mussolini", "Joseph Stalin", "Winston Churchill"],
        "answer": "Adolf Hitler"
    },
    {
        "question": "In which year did the United States declare independence from Great Britain?",
        "options": ["1774", "1776", "1781", "1783"],
        "answer": "1776"
    },
    {
        "question": "Who wrote the 'Communist Manifesto'?",
        "options": ["Karl Marx", "Friedrich Nietzsche", "Adam Smith", "John Locke"],
        "answer": "Karl Marx"
    },
    {
        "question": "Which famous king built the Palace of Versailles?",
        "options": ["King Louis XIV", "King Henry VIII", "King Charles I", "King Philip II"],
        "answer": "King Louis XIV"
    },
    {
        "question": "Which civilization built the city of Troy?",
        "options": ["Greek", "Egyptian", "Mesopotamian", "Hittite"],
        "answer": "Greek"
    }],

    "Modern Technology" :
     [{
        "question": "What does CPU stand for?",
        "options": ["Central Processing Unit", "Computer Personal Unit", "Control Panel Unit", "Central Power Unit"],
        "answer": "Central Processing Unit"
    },
    {
        "question": "What is the world's largest social media platform?",
        "options": ["Twitter", "Instagram", "Facebook", "Snapchat"],
        "answer": "Facebook"
    },
    {
        "question": "What does HTML stand for?",
        "options": ["Hypertext Markup Language", "Hyperlink Text Markup Language", "Home Tool Markup Language", "Hypertext Technical Markup Language"],
        "answer": "Hypertext Markup Language"
    },
    {
        "question": "Which company developed the iPhone?",
        "options": ["Apple", "Samsung", "Google", "Microsoft"],
        "answer": "Apple"
    },
    {
        "question": "What is the most popular programming language in 2021?",
        "options": ["Python", "JavaScript", "Java", "C++"],
        "answer": "Python"
    },
    {
        "question": "What does VPN stand for?",
        "options": ["Virtual Private Network", "Virtual Public Network", "Visual Private Network", "Visual Public Network"],
        "answer": "Virtual Private Network"
    },
    {
        "question": "Which company is known for its gaming console 'PlayStation'?",
        "options": ["Microsoft", "Nintendo", "Sony", "Sega"],
        "answer": "Sony"
    },
    {
        "question": "What is the world's largest online marketplace?",
        "options": ["Amazon", "eBay", "Alibaba", "Etsy"],
        "answer": "Amazon"
    },
    {
        "question": "Which company developed the Windows operating system?",
        "options": ["Apple", "Microsoft", "Google", "Linux"],
        "answer": "Microsoft"
    },
    {
        "question": "What is the term used for a malicious software that can replicate itself and spread to other computers?",
        "options": ["Malware", "Spyware", "Virus", "Phishing"],
        "answer": "Virus"
    },
    {
        "question": "What is the popular video-sharing platform owned by Google?",
        "options": ["YouTube", "Vimeo", "Dailymotion", "TikTok"],
        "answer": "YouTube"
    },
    {
        "question": "What is the term used for a small piece of code that performs a specific task?",
        "options": ["Algorithm", "Function", "Variable", "Script"],
        "answer": "Function"
    },
    {
        "question": "Which company is known for its search engine?",
        "options": ["Yahoo", "Bing", "Google", "DuckDuckGo"],
        "answer": "Google"
    },
    {
        "question": "What is the term used for a wireless technology that allows data to be transferred over short distances?",
        "options": ["Bluetooth", "Wi-Fi", "NFC", "LTE"],
        "answer": "Bluetooth"
    },
    {
        "question": "Which company is known for its electric cars?",
        "options": ["Tesla", "Toyota", "Ford", "Honda"],
        "answer": "Tesla"
    },
    {
        "question": "What is the term used for a storage device that uses flash memory and has no moving parts?",
        "options": ["Hard Disk Drive", "Solid-State Drive", "USB Drive", "CD-ROM"],
        "answer": "Solid-State Drive"
    },
    {
        "question": "Which company is known for its streaming platform 'Netflix'?",
        "options": ["Hulu", "Disney", "Amazon", "Netflix"],
        "answer": "Netflix"
    },
    {
        "question": "What is the term used for a software program that can replicate itself and spread to other computers?",
        "options": ["Malware", "Spyware", "Virus", "Worm"],
        "answer": "Worm"
    },
    {
        "question": "Which company developed the Android operating system?",
        "options": ["Apple", "Samsung", "Google", "Microsoft"],
        "answer": "Google"
    },
    {
        "question": "What is the term used for a device that converts digital signals into analog signals and vice versa?",
        "options": ["Modem", "Router", "Switch", "Hub"],
        "answer": "Modem"
    }],

    "Music" :
     [{
        "question": "Who is known as the 'King of Pop'?",
        "options": ["Michael Jackson", "Elvis Presley", "Prince", "Stevie Wonder"],
        "answer": "Michael Jackson"
    },
    {
        "question": "Which band is known for the hit song 'Bohemian Rhapsody'?",
        "options": ["The Beatles", "Queen", "Led Zeppelin", "The Rolling Stones"],
        "answer": "Queen"
    },
    {
        "question": "Who is the lead vocalist of the band Coldplay?",
        "options": ["Chris Martin", "Bono", "Thom Yorke", "Adam Levine"],
        "answer": "Chris Martin"
    },
    {
        "question": "Which artist released the album 'Lemonade' in 2016?",
        "options": ["Taylor Swift", "Beyoncé", "Rihanna", "Adele"],
        "answer": "Beyoncé"
    },
    {
        "question": "Who is the guitarist of the band Led Zeppelin?",
        "options": ["Jimmy Page", "Eric Clapton", "Jimi Hendrix", "Keith Richards"],
        "answer": "Jimmy Page"
    },
    {
        "question": "Which artist has won the most Grammy Awards?",
        "options": ["Beyoncé", "Michael Jackson", "Taylor Swift", "Beyoncé", "Aretha Franklin"],
        "answer": "Beyoncé"
    },
    {
        "question": "Who wrote the song 'Imagine'?",
        "options": ["John Lennon", "Paul McCartney", "Bob Dylan", "Elton John"],
        "answer": "John Lennon"
    },
    {
        "question": "Which artist released the album 'Thriller' in 1982?",
        "options": ["Michael Jackson", "Elvis Presley", "Prince", "Stevie Wonder"],
        "answer": "Michael Jackson"
    },
    {
        "question": "Who is the lead vocalist of the band U2?",
        "options": ["Bono", "Chris Martin", "Thom Yorke", "Adam Levine"],
        "answer": "Bono"
    },
    {
        "question": "Which artist released the album '21' in 2011?",
        "options": ["Taylor Swift", "Beyoncé", "Rihanna", "Adele"],
        "answer": "Adele"
    },
    {
        "question": "Who is the guitarist of the band Queen?",
        "options": ["Brian May", "Jimmy Page", "Eric Clapton", "Keith Richards"],
        "answer": "Brian May"
    },
    {
        "question": "Which artist has won the most Academy Awards for Best Original Song?",
        "options": ["Elton John", "Stevie Wonder", "Hans Zimmer", "Alan Menken"],
        "answer": "Alan Menken"
    },
    {
        "question": "Who wrote the song 'Hey Jude'?",
        "options": ["John Lennon", "Paul McCartney", "Bob Dylan", "Elton John"],
        "answer": "Paul McCartney"
    },
    {
        "question": "Which artist released the album 'Purple Rain' in 1984?",
        "options": ["Michael Jackson", "Elvis Presley", "Prince", "Stevie Wonder"],
        "answer": "Prince"
    },
    {
        "question": "Who is the lead vocalist of the band Radiohead?",
        "options": ["Thom Yorke", "Bono", "Chris Martin", "Adam Levine"],
        "answer": "Thom Yorke"
    },
    {
        "question": "Which artist released the album 'Good Girl Gone Bad' in 2007?",
        "options": ["Taylor Swift", "Beyoncé", "Rihanna", "Adele"],
        "answer": "Rihanna"
    },
    {
        "question": "Who is the guitarist of the band The Rolling Stones?",
        "options": ["Keith Richards", "Jimmy Page", "Eric Clapton", "Jimi Hendrix"],
        "answer": "Keith Richards"
    },
    {
        "question": "Which artist has won the most Billboard Music Awards?",
        "options": ["Drake", "Taylor Swift", "Beyoncé", "Adele"],
        "answer": "Drake"
    },
    {
        "question": "Who wrote the song 'Like a Rolling Stone'?",
        "options": ["John Lennon", "Bob Dylan", "Paul McCartney", "Elton John"],
        "answer": "Bob Dylan"
    },
    {
        "question": "Which artist released the album 'Songs in the Key of Life' in 1976?",
        "options": ["Michael Jackson", "Elvis Presley", "Prince", "Stevie Wonder"],
        "answer": "Stevie Wonder"
    }],

    "Books" :
     [{
        "question": "Who wrote the 'Harry Potter' series?",
        "options": ["J.R.R. Tolkien", "J.K. Rowling", "George R.R. Martin", "Stephenie Meyer"],
        "answer": "J.K. Rowling"
    },
    {
        "question": "Which novel is set in the fictional land of Narnia?",
        "options": ["The Lion, the Witch and the Wardrobe", "The Hobbit", "Pride and Prejudice", "To Kill a Mockingbird"],
        "answer": "The Lion, the Witch and the Wardrobe"
    },
    {
        "question": "Who wrote the novel 'To Kill a Mockingbird'?",
        "options": ["F. Scott Fitzgerald", "Harper Lee", "John Steinbeck", "Jane Austen"],
        "answer": "Harper Lee"
    },
    {
        "question": "Which book is the first in the 'A Song of Ice and Fire' series?",
        "options": ["A Game of Thrones", "The Fellowship of the Ring", "1984", "The Catcher in the Rye"],
        "answer": "A Game of Thrones"
    },
    {
        "question": "Who is the author of the 'Lord of the Rings' trilogy?",
        "options": ["J.R.R. Tolkien", "J.K. Rowling", "George R.R. Martin", "Stephenie Meyer"],
        "answer": "J.R.R. Tolkien"
    },
    {
        "question": "Which classic novel is set during the American Civil War?",
        "options": ["Gone with the Wind", "Moby-Dick", "The Great Gatsby", "Jane Eyre"],
        "answer": "Gone with the Wind"
    },
    {
        "question": "Who wrote the 'Percy Jackson & the Olympians' series?",
        "options": ["Rick Riordan", "Veronica Roth", "Suzanne Collins", "J.K. Rowling"],
        "answer": "Rick Riordan"
    },
    {
        "question": "Which novel is set in the dystopian society of Panem?",
        "options": ["The Hunger Games", "The Giver", "Brave New World", "Fahrenheit 451"],
        "answer": "The Hunger Games"
    },
    {
        "question": "Who is the author of the 'Game of Thrones' series?",
        "options": ["J.R.R. Tolkien", "J.K. Rowling", "George R.R. Martin", "Stephenie Meyer"],
        "answer": "George R.R. Martin"
    },
    {
        "question": "Which novel is a coming-of-age story set in 1960s Mississippi?",
        "options": ["To Kill a Mockingbird", "The Catcher in the Rye", "The Help", "The Outsiders"],
        "answer": "The Help"
    },
    {
        "question": "Who wrote the 'Twilight' series?",
        "options": ["J.R.R. Tolkien", "J.K. Rowling", "George R.R. Martin", "Stephenie Meyer"],
        "answer": "Stephenie Meyer"
    },
    {
        "question": "Which novel is set in the fictional town of Maycomb, Alabama?",
        "options": ["To Kill a Mockingbird", "1984", "Pride and Prejudice", "The Great Gatsby"],
        "answer": "To Kill a Mockingbird"
    },
    {
        "question": "Who is the author of the 'Chronicles of Narnia' series?",
        "options": ["C.S. Lewis", "J.R.R. Tolkien", "Roald Dahl", "Lewis Carroll"],
        "answer": "C.S. Lewis"
    },
    {
        "question": "Which novel is set in the post-apocalyptic district of Panem?",
        "options": ["The Hunger Games", "Divergent", "The Maze Runner", "The Fault in Our Stars"],
        "answer": "The Hunger Games"
    },
    {
        "question": "Who wrote the novel 'Pride and Prejudice'?",
        "options": ["F. Scott Fitzgerald", "Jane Austen", "George Orwell", "Leo Tolstoy"],
        "answer": "Jane Austen"
    },
    {
        "question": "Which book is the first in the 'Harry Potter' series?",
        "options": ["Harry Potter and the Sorcerer's Stone", "Harry Potter and the Chamber of Secrets", "Harry Potter and the Prisoner of Azkaban", "Harry Potter and the Goblet of Fire"],
        "answer": "Harry Potter and the Sorcerer's Stone"
    },
    {
        "question": "Who is the author of the 'Divergent' series?",
        "options": ["Rick Riordan", "Veronica Roth", "Suzanne Collins", "J.K. Rowling"],
        "answer": "Veronica Roth"
    },
    {
        "question": "Which novel is set in a future society where books are banned?",
        "options": ["Fahrenheit 451", "Brave New World", "1984", "The Giver"],
        "answer": "Fahrenheit 451"
    },
    {
        "question": "Who is the author of the 'Hunger Games' series?",
        "options": ["Rick Riordan", "Veronica Roth", "Suzanne Collins", "J.K. Rowling"],
        "answer": "Suzanne Collins"
    },
    {
        "question": "Which novel is set in the fictional district of Oceania?",
        "options": ["1984", "Brave New World", "The Giver", "Fahrenheit 451"],
        "answer": "1984"
    }],

    "Movies" :
     [{
        "question": "Who wrote the 'Harry Potter' series?",
        "options": ["J.R.R. Tolkien", "J.K. Rowling", "George R.R. Martin", "Stephenie Meyer"],
        "answer": "J.K. Rowling"
    },
    {
        "question": "Which novel is set in the fictional land of Narnia?",
        "options": ["The Lion, the Witch and the Wardrobe", "The Hobbit", "Pride and Prejudice", "To Kill a Mockingbird"],
        "answer": "The Lion, the Witch and the Wardrobe"
    },
    {
        "question": "Who wrote the novel 'To Kill a Mockingbird'?",
        "options": ["F. Scott Fitzgerald", "Harper Lee", "John Steinbeck", "Jane Austen"],
        "answer": "Harper Lee"
    },
    {
        "question": "Which book is the first in the 'A Song of Ice and Fire' series?",
        "options": ["A Game of Thrones", "The Fellowship of the Ring", "1984", "The Catcher in the Rye"],
        "answer": "A Game of Thrones"
    },
    {
        "question": "Who is the author of the 'Lord of the Rings' trilogy?",
        "options": ["J.R.R. Tolkien", "J.K. Rowling", "George R.R. Martin", "Stephenie Meyer"],
        "answer": "J.R.R. Tolkien"
    },
    {
        "question": "Which classic novel is set during the American Civil War?",
        "options": ["Gone with the Wind", "Moby-Dick", "The Great Gatsby", "Jane Eyre"],
        "answer": "Gone with the Wind"
    },
    {
        "question": "Who wrote the 'Percy Jackson & the Olympians' series?",
        "options": ["Rick Riordan", "Veronica Roth", "Suzanne Collins", "J.K. Rowling"],
        "answer": "Rick Riordan"
    },
    {
        "question": "Which novel is set in the dystopian society of Panem?",
        "options": ["The Hunger Games", "The Giver", "Brave New World", "Fahrenheit 451"],
        "answer": "The Hunger Games"
    },
    {
        "question": "Who is the author of the 'Game of Thrones' series?",
        "options": ["J.R.R. Tolkien", "J.K. Rowling", "George R.R. Martin", "Stephenie Meyer"],
        "answer": "George R.R. Martin"
    },
    {
        "question": "Which novel is a coming-of-age story set in 1960s Mississippi?",
        "options": ["To Kill a Mockingbird", "The Catcher in the Rye", "The Help", "The Outsiders"],
        "answer": "The Help"
    },
    {
        "question": "Who wrote the 'Twilight' series?",
        "options": ["J.R.R. Tolkien", "J.K. Rowling", "George R.R. Martin", "Stephenie Meyer"],
        "answer": "Stephenie Meyer"
    },
    {
        "question": "Which novel is set in the fictional town of Maycomb, Alabama?",
        "options": ["To Kill a Mockingbird", "1984", "Pride and Prejudice", "The Great Gatsby"],
        "answer": "To Kill a Mockingbird"
    },
    {
        "question": "Who is the author of the 'Chronicles of Narnia' series?",
        "options": ["C.S. Lewis", "J.R.R. Tolkien", "Roald Dahl", "Lewis Carroll"],
        "answer": "C.S. Lewis"
    },
    {
        "question": "Which novel is set in the post-apocalyptic district of Panem?",
        "options": ["The Hunger Games", "Divergent", "The Maze Runner", "The Fault in Our Stars"],
        "answer": "The Hunger Games"
    },
    {
        "question": "Who wrote the novel 'Pride and Prejudice'?",
        "options": ["F. Scott Fitzgerald", "Jane Austen", "George Orwell", "Leo Tolstoy"],
        "answer": "Jane Austen"
    },
    {
        "question": "Which book is the first in the 'Harry Potter' series?",
        "options": ["Harry Potter and the Sorcerer's Stone", "Harry Potter and the Chamber of Secrets", "Harry Potter and the Prisoner of Azkaban", "Harry Potter and the Goblet of Fire"],
        "answer": "Harry Potter and the Sorcerer's Stone"
    },
    {
        "question": "Who is the author of the 'Divergent' series?",
        "options": ["Rick Riordan", "Veronica Roth", "Suzanne Collins", "J.K. Rowling"],
        "answer": "Veronica Roth"
    },
    {
        "question": "Which novel is set in a future society where books are banned?",
        "options": ["Fahrenheit 451", "Brave New World", "1984", "The Giver"],
        "answer": "Fahrenheit 451"
    },
    {
        "question": "Who is the author of the 'Hunger Games' series?",
        "options": ["Rick Riordan", "Veronica Roth", "Suzanne Collins", "J.K. Rowling"],
        "answer": "Suzanne Collins"
    },
    {
        "question": "Which novel is set in the fictional district of Oceania?",
        "options": ["1984", "Brave New World", "The Giver", "Fahrenheit 451"],
        "answer": "1984"
    }],

    "Random" :
     [{
        "question": "What is the capital city of Australia?",
        "options": ["Sydney", "Melbourne", "Canberra", "Perth"],
        "answer": "Canberra"
    },
    {
        "question": "Which planet is known as the 'Red Planet'?",
        "options": ["Venus", "Mars", "Jupiter", "Saturn"],
        "answer": "Mars"
    },
    {
        "question": "What is the chemical symbol for gold?",
        "options": ["Au", "Ag", "Fe", "Hg"],
        "answer": "Au"
    },
    {
        "question": "Who painted the 'Mona Lisa'?",
        "options": ["Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso", "Michelangelo"],
        "answer": "Leonardo da Vinci"
    },
    {
        "question": "What is the tallest mountain in the world?",
        "options": ["Mount Everest", "K2", "Kangchenjunga", "Makalu"],
        "answer": "Mount Everest"
    },
    {
        "question": "What is the largest ocean on Earth?",
        "options": ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
        "answer": "Pacific Ocean"
    },
    {
        "question": "Who wrote the play 'Romeo and Juliet'?",
        "options": ["William Shakespeare", "Arthur Miller", "Tennessee Williams", "Oscar Wilde"],
        "answer": "William Shakespeare"
    },
    {
        "question": "Which country is known as the 'Land of the Rising Sun'?",
        "options": ["China", "Japan", "India", "South Korea"],
        "answer": "Japan"
    },
    {
        "question": "What is the largest organ in the human body?",
        "options": ["Heart", "Brain", "Liver", "Skin"],
        "answer": "Skin"
    },
    {
        "question": "Who is the author of the 'Harry Potter' series?",
        "options": ["J.R.R. Tolkien", "J.K. Rowling", "George R.R. Martin", "Stephenie Meyer"],
        "answer": "J.K. Rowling"
    },
    {
        "question": "Which animal is known as the 'King of the Jungle'?",
        "options": ["Tiger", "Lion", "Elephant", "Giraffe"],
        "answer": "Lion"
    },
    {
        "question": "What is the largest organ in the human body?",
        "options": ["Heart", "Brain", "Liver", "Skin"],
        "answer": "Skin"
    },
    {
        "question": "Who painted the ceiling of the Sistine Chapel?",
        "options": ["Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso", "Michelangelo"],
        "answer": "Michelangelo"
    },
    {
        "question": "Which country is known as the 'Land Down Under'?",
        "options": ["United States", "Canada", "Australia", "New Zealand"],
        "answer": "Australia"
    },
    {
        "question": "What is the symbol for the element oxygen?",
        "options": ["O", "H", "C", "N"],
        "answer": "O"
    },
    {
        "question": "Who wrote the novel '1984'?",
        "options": ["George Orwell", "F. Scott Fitzgerald", "Jane Austen", "Leo Tolstoy"],
        "answer": "George Orwell"
    },
    {
        "question": "Which country is known for the Taj Mahal?",
        "options": ["India", "China", "Egypt", "Italy"],
        "answer": "India"
    },
    {
        "question": "What is the largest continent in the world?",
        "options": ["Europe", "Asia", "Africa", "North America"],
        "answer": "Asia"
    },
    {
        "question": "Who painted the 'Starry Night'?",
        "options": ["Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso", "Michelangelo"],
        "answer": "Vincent van Gogh"
    },
    {
        "question": "What is the capital city of France?",
        "options": ["London", "Berlin", "Paris", "Rome"],
        "answer": "Paris"
    }]

 }

 # Function to ask a question and check the answer
def ask_question(question, options, answer):
    print(question)
    for i, option in enumerate(options):
        print(f"{i+1}. {option}")
    user_answer = input("Enter your answer (1-4): ")
    if options[int(user_answer)-1] == answer:
        print("Correct!")
        return True
    else:
        print("Incorrect!")
        return False


# Main program loop
def start_quiz():
    print("Welcome to the Quiz Game!")
    print("Select a domain:")
    print("1. Arts and Culture")
    print("2. Funny")
    print("3. Geography")
    print("4. History")
    print("5. Modern Technology")
    print("6. Music")
    print("7. Books")
    print("8. Movies")
    print("9. Random")

    domain = input("Enter the number corresponding to the domain: ")

    # Validate domain selection
    while domain not in ["1", "2", "3", "4", "5", "6", "7", "8", "9"]:
      print("Invalid input. Please try again.")
      domain = input("Enter the number corresponding to the domain: ")

    # Convert domain to appropriate key
    if domain == "1":
      domain_key = "Arts and Culture"
    elif domain == "2":
      domain_key = "Funny"
    elif domain == "3":
      domain_key = "Geography"
    elif domain == "4":
      domain_key = "History"
    elif domain == "5":
      domain_key = "Modern Technology"
    elif domain == "6":
      domain_key = " Music"
    elif domain == "7":
      domain_key = " Books"
    elif domain == "8":
      domain_key = " Movies"
    elif domain == "9":
      domain_key = "Random"

    # Get questions for the selected domain
    selected_questions = questions[domain_key]

    # Iterate through the questions
    score = 0
    for question in selected_questions:
      if ask_question(question["question"], question["options"], question["answer"]):
        score += 1
        print()

    # Display final score
    total_questions = len(selected_questions)
    print("Quiz completed!")
    print(f"Your score: {score}/{total_questions}")

# Start the quiz
start_quiz()