# -*- coding: utf-8 -*-
"""PasswordGenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16uVBRRalSTS_EuI1v3B26InhgXNiH8dp
"""

import random
import string

def generate_password(length):
    characters = string.ascii_letters + string.digits + '~`!@#$%^&*()_-+={[}]|\\:;"\'<,>.?/'
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

while True:
    length_str = input("Enter the length of the password: ")
    if length_str.isdigit():
        length = int(length_str)
        password = generate_password(length)
        print("Generated Password:", password)
        break
    else:
        print("Invalid length. Please enter a valid positive integer.")